### ISSUE TITLE
Assign object reference to a Session

### ISSUE THREAD

**Issue by digao-dalpiaz** [kenkendk/ceenhttpd#18]
Hey,

I'm using Ceen.Httpd.Handler.SessionHandler to handle sessions context.

So, there is a IHttpContext.Session (Dictionary), to assign Key and Value strings.

**I wonder if can I assign an object reference to the session context.**

Until now I have a separated list of objects with an ID, so the context has a "ID" key with a identity value to manually reference list index. But, the problem is to know when the session context ends, so I can release my object.

Better method will be assign object directly to the session context, of course.

Thanks,
Best regards.

**Comment by kenkendk** [comment]
The idea is that the server can be restarted at random intervals (when deploying updates for instance).
For this to work without loosing state, you need to store the objects you reference, outside the current process. You cannot do this with an object reference (at least not directly).

However, if you do not care about the safe restarting feature, it is not a problem to store object references in the running process. Unfortunately, I did not have a need for this feature myself, so there is nothing built-in to support it.

You can re-purpose the `Ceen.LRUCache` class to periodically expire items, and then have it store a `Dictionary<string, object>` reference. Then you just need to use the current session ID as the key to the LRUCache, and it will get you the current session.

**Comment by digao-dalpiaz** [comment]
Hey,
Thanks for the answers.

About loosing session in server restart is not a problem, because in my server the session should be really dropped when server restarts.

About Ceen.LRUCache, if I understood, it will work as a List of objects with an ID and object, so I manually link the ID with session ID. This is what I'm already doing, with a list of objects containing an ID property.

But, in both cases, isn't a performative way to work with sessions, because when we have a lot of sessions, to get the object of one sessions, I should iterate a list finding the sessions ID to get the object.

So, following the same idea as other components, it will be interesting if we have a property in session context to assign a pointer reference, so we can read directly the object of session context, without iterating a list.

Another question is about session termination. I can't find a way to intercept the session close moment, to release my session object instance.

Thanks again.
Great http server. 👍

**Comment by kenkendk** [comment]
I made a new extension for this:
https://github.com/kenkendk/ceenhttpd/blob/master/Ceen.Extras/InMemorySession.cs

The current `IStorage` model is tied closely to having persistent storage, so the session is purely `IDictionary<string, string>`. But in your case you want only in-memory storage, so we want `Dictionary<string, object>`.

You can access the current state with (remember `using Ceen.Extras.InMemorySession;`) inside your handler like this:
https://github.com/kenkendk/ceenhttpd/blob/master/Unittests/InMemorySessionTests.cs#L51

The implementation uses a dictionary to look up the session, so even with many sessions it should be really fast. It does, however, iterate over the list of sessions when finding out which sessions to expire. The expiration is throttled to run at most every 5 seconds, but if you have a high load, it might be a problem. I am not sure how to solve this, as you need a list sorted both by ID and by expiration time to be able to update the expiration time as well as find the expired items. We could register a timer on each session-item, and then register in a shared list, but if you have a lot, I am not sure how it performs with a large number of waiting tasks.

I cannot find a good way to add an expiration callback to `IStorage`, as it would need to invoke a function across app-domains (or processes). For the `InMemorySession`, you can either register on the static member `Ceen.Extras.InMemorySession.InMemorySession.SessionExpired`, or subclass the session handler, like here:
https://github.com/kenkendk/ceenhttpd/blob/master/Unittests/InMemorySessionTests.cs#L31

Hope this does what you are looking for.

**Comment by digao-dalpiaz** [comment]
Hey @kenkendk,

That's awesome. It's exactly what I'm looking for...

I'll use this extension in my Web Server application.

Thank you very much.
