### ISSUE TITLE
"Dynamic content" example does not work

### ISSUE THREAD

**Issue by yuppox** [kenkendk/ceenhttpd#24]
There seems to be information missing from this example. I get multiple errors trying to use it.

There is no definition for `WriteAllJsonAsync` or `SetNonCacheable`. Plus, the `IHttpModule` interface says that two functions are not implemented.

The references should also include:
```
using System;
**using System.Web;**
using Ceen.Httpd;
using Ceen.Httpd.Handler;
using Ceen.Httpd.Logging;
using System.Net;
using System.Threading;
using Newtonsoft.Json;
```

**Comment by kenkendk** [comment]
I have added some extra includes, is that sufficient? Otherwise, can you make a PR with the changes?

**Comment by kenkendk** [comment]
Assuming fixed, feel free to re-open if that is not the case.
