### ISSUE TITLE
application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by danielpaten** [kenkendk/ceenhttpd#25]
Hello,

In HttpRequest.cs, you test the content type:
if (string.Equals("application/x-www-form-urlencoded", this.ContentType))

But in some case the browser send "Content-Type: application/x-www-form-urlencoded; charset=UTF-8"
So the test fails ...

Congratulations again for this superb work.
Thank you

Daniel

**Comment by kenkendk** [comment]
Thanks for reporting. This is now fixed, and also applies the charset when decoding the data.
