### ISSUE TITLE
URL not correctly decoded.

### ISSUE THREAD

**Issue by danielpaten** [kenkendk/ceenhttpd#26]
Hello,

I have some problem with URL not correctly decoded.
Many Web browsers escape spaces inside of URIs into plus ("+") characters (Chrome on Windows …)
According the Microsoft Doc the use of Uri.UnescapeDataString method does not convert plus characters into spaces.

So solution :  
text = text.Replace("+", " ");
text = System.Uri.UnescapeDataString(text);

Or 
use System.Web.HttpUtility.UrlDecode instead

Best continuation 
Daniel

**Comment by kenkendk** [comment]
That was a bit of a rabbit hole, but it is now fixed such that `+` on right-hand side of the `?` in the url.
The change was based on this answer: https://stackoverflow.com/a/1634293/

**Comment by danielpaten** [comment]
Thank you,

Everything works like a charm.

Thank you
And happy new year 2021.
Daniel

PS: For your information, the links to the issues in comments in code source contain a typo, an "s" is missing at issue.
https://github.com/kenkendk/ceenhttpd/issue/26 ==> not working
https://github.com/kenkendk/ceenhttpd/issues/26 == Good :-)
