### ISSUE TITLE
Support WebSocket?

### ISSUE THREAD

**Issue by MacKey-255** [kenkendk/ceenhttpd#30]
Hi, I found amazing this library, wanted to know if you have support for WebSocket? SAlu2s

**Comment by kenkendk** [comment]
Hi, thanks for the kind words.

There is no direct support for WebSockets, but the framework is flexible enough that you can add a WebSocket handler.

**Comment by MacKey-255** [comment]
I am going to create a WebSocket Module. Thanks for answering
