### ISSUE TITLE
IVirtualFileSystem interface visibility

### ISSUE THREAD

**Issue by vvhitesmoke** [kenkendk/ceenhttpd#5]
I'm trying to implement own VirtualFileSystem - unfortunately, the IVirtualFileSystem interface is not visible: it is defined inside FileHandler class, should be outside, so adding custom VirtualFileSystem is not possible. Is there any (unknown for me) reason for that this is hidden? If not, would I like to ask you about change this?
IMHO the best solution will be splitting FileHandler.cs file into two parts: one containing the FileSystem, and the second containing FileHandler without own FileSystem implementation.

**Comment by kenkendk** [comment]
That is a mistake on my behalf. The `IVirtualFileSystem` is supposed to be public visible. I will fix and create a new nuget package.

**Comment by kenkendk** [comment]
Hmm, just looked, and it is indeed public.
This works for me and compiles fine:

```csharp
private class MyVFS : Ceen.Httpd.Handler.FileHandler.IVirtualFileSystem
{
	public Task<bool> FileExistsAsync(string path) => throw new NotImplementedException();
	public Task<bool> FolderExistsAsync(string path) => throw new NotImplementedException();
	public Task<DateTime> GetLastFileWriteTimeUtcAsync(string path) => throw new NotImplementedException();
	public Task<string> GetMimeTypePathAsync(string path) => throw new NotImplementedException();
	public Task<Stream> OpenReadAsync(string path) => throw new NotImplementedException();
}
```

**Comment by vvhitesmoke** [comment]
Hmmm... Doesn't work for me :(
I'm using VS 2017 (15.9.4) and installed latest Ceen.* packages from NuGet. The project is class library (.net framework 4.7.2). Below part of my packages.config file:
  <package id="Ceen.Httpd" version="0.9.4" targetFramework="net472" />
  <package id="Ceen.Mvc" version="0.9.4" targetFramework="net472" />
  <package id="Ceen.Security" version="0.9.4" targetFramework="net472" />

And can't see the FileHandler constructor, which uses IVirtualFileSystem as first parameter: FileHandler(IVirtualFileSystem vfs, Func<IHttpRequest, string, string> mimetypelookup = null) - probably VS is hidding this for any reasons (because of unknown type of the first parameter ???).

All other seems to work :) (thanks for your great work!)

**Comment by vvhitesmoke** [comment]
Ok, so all is clear now :) Thanks for very fast reaction :) :1st_place_medal:

**Comment by kenkendk** [comment]
New version `0.9.5` is uploaded to NuGet and will be available shortly.
